{'detail': 'Vertex AI error: 500: No image data returned from Imagen 4.\nTraceback:\nTraceback (most recent call last):\n  File "C:\\Users\\p90022569\\Downloads\\image_gen\\main.py", line 89, in generate_image\n    raise HTTPException(\nfastapi.exceptions.HTTPException: 500: No image data returned from Imagen 4.\n'}
